# Site settings
title: Dee Broomhead

# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Dee Broomhead
user_description: As a trained anthropological researcher, I have experience with both quantitative and qualitative projects. I am passionate about the ways that human-focused research can foster meaningful connections and improve the lives of others in new ways. Through designing my own research projects I have been able to explore a range of topics including consumer perceptions of authenticity, work environments, and brand globalization strategy.
user_title: Researcher
email: deeann824@gmail.com

exclude: ['package.json', 'src' , 'node_modules']
