# Site settings
title: Dee Broomhead

# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Dee Broomhead
user_description: I am a trained anthropological researcher with qualitative and quantitative experience. I have designed and carried out projects on consumer perceptions of authenticity, work environments, and brand globalization. I am passionate about the ways human-focused research can foster meaningful connections and improve the lives of others.
user_title: Researcher
email: deeann824@gmail.com

exclude: ['package.json', 'src' , 'node_modules']
